displayName: ondemand traefik plugin
type: middleware

import: github.com/acouvreur/traefik-ondemand-plugin

summary: 'Scale swarm services on demand when requested'

testData:
  serviceUrl: http://ondemand:10000
  name: TRAEFIK_HACKATHON_whoami
  timeout: 60
  