displayName: Containers On Demand
type: middleware

import: github.com/acouvreur/traefik-ondemand-plugin

summary: 'Scale swarm services down to zero after a timeout and bring them back up on demand'

testData:
  serviceUrl: http://ondemand:10000
  name: TRAEFIK_HACKATHON_whoami
  timeout: 1m
  