http:
  middlewares:
    ondemand:
      plugin:
        ondemand:
          serviceurl: http://ondemand:10000
          name: TRAEFIK_HACKATHON_whoami
          timeout: 1m

  services:
    whoami:
      loadBalancer:
        servers:
        - url: "http://whoami:80"

  routers:
    whoami:
      rule: PathPrefix(`/whoami`)
      entryPoints:
        - "http"
      middlewares:
        - ondemand
      service: "whoami"