version: "3.9"

services:
  ondemand:
    image: gchr.io/acouvreur/traefik-ondemand-service:latest
    command:
      - --swarmMode=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik