version: "3.9"

services:
  sablier:
    image: gchr.io/acouvreur/sablier:latest
    command:
      - --swarmMode=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik