pilot:
  token: "$TRAEFIK_PILOT_TOKEN"

api:
  dashboard: true
  insecure: true

experimental:
  localPlugins:
    ondemand:  
      moduleName: github.com/acouvreur/traefik-ondemand-plugin

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
  file:
    filename: "/etc/traefik/config.yml"
    watch: true