name: Build Sablier plugins

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  traefik:
    name: Build Sablier for Traefik middleware
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: cd plugins/traefik && go build -v .

      - name: Test
        run: cd plugins/traefik && go test -v ./...

  traefik_e2e:
    name: Run Sablier E2E tests for Traefik middleware
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider: [docker_classic, docker_swarm]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          buildkitd-flags: --debug
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          load: true
          context: .
          tags: ghcr.io/acouvreur/sablier:local

      - name: Test ${{ matrix.provider }}
        run: cd plugins/traefik/e2e && bash ./${{ matrix.provider }}.sh